flags: {}
packages:
- '.'
- lib/theory/
- lib/term/
- lib/utils/
extra-deps: []
resolver: lts-8.15

# Uncomment the following if you use docker
# docker:
#   enable: true

# for GHC 7.10 use:
# lts-6.27
